version: '3.2'

services:

    mongo:
      image: mongo:{{ MONGO_VERSION }}
      entrypoint: [ "/usr/bin/mongod", "--replSet", "{{ REPLICASET_NAME }}", "--journal", "--smallfiles"]
      ports:
        - {{ MONGO_PORT }}:27017
      # The usage of volume provides persistence, but may work correctly only with 1 volume per node (that's why global mode is recommended)
      volumes:
        - mongodata:/data/db
      networks:
        - backend
      deploy:
        mode: global
        restart_policy:
          condition: on-failure
        update_config:
          parallelism: 1
          delay: 1m30s

    mongo-controller:
      image: martel/mongo-replica-ctrl:latest
      volumes:
        # TODO: Avoid exposing the docker socket (security issue)
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - OVERLAY_NETWORK_NAME={{ OVERLAY_NETWORK_NAME }}
        - MONGO_SERVICE_NAME={{ STACK_NAME }}_mongo
        - REPLICASET_NAME={{ REPLICASET_NAME }}
        - MONGO_PORT=27017
      entrypoint: python /src/replica_ctrl.py
      networks:
          - backend
      depends_on:
          - "mongo"
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.role==manager]
        restart_policy:
          condition: on-failure

volumes:
  # External true ensures that the volume is not re-created if already present
  mongodata:
    external: true

networks:
    default:
        driver_opts:
            com.docker.network.driver.mtu: 1500
    backend:
        driver: overlay
        external: true # uncomment if you want to re-use and existing network! if not it will create a network dedicated to the stack!
