version: '3'

services:
  mongo:
    image: mongo:3.2
    command: --nojournal
    restart: always

  orion:
    depends_on:
      - mongo
    image: fiware/orion
    ports:
      - "1026:1026"
    command: -dbhost mongo
    restart: always
