development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mastermind_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("MASTERMIND_DB_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("MASTERMIND_DB_HOST") { "127.0.0.1" } %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mastermind_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("MASTERMIND_DB_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("MASTERMIND_DB_HOST") { "127.0.0.1" } %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mastermind_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("MASTERMIND_DB_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("MASTERMIND_DB_HOST") { "127.0.0.1" } %>
