version: '3'

services:

    mongo:
      image: mongo:3.2
      command: --nojournal

    orion:
      image: fiware/orion
      links:
        - mongo
      ports:
        - 1026:1026
      command: -dbhost mongo
